API_KEY='c9GBPlueMjR9lKoDimcgkMhPP7WeLF8zgHMkQZms7nbXR5amXv4VlqWWokjKXzuq'
API_SECRET='ie6ZKHUHVTbFDFUwYtZrozqv79iIOisPJwhKzaE9jC5iKWSpFJFvZE467UlHhXhi'


EnableBinanceApi =  True
TRADE_SYMBOL = 'ETHBUSD'
TRADE_QUANTITY = 0.005
Coin = 'ETH'
Usd = 'BUSD'